tags:
  - name: api
    description: 获取前端某个项目版本API

servers:
  - url: http://localhost:9000/
    description: 开发环境API url

paths:
  /v1/login:
    post:
      tags: 
      - user
      summary: "登陆"
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - Action
              - username
              - password
            properties:
              Action:
                type: string
                example: Login
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /v1/register:
    post:
      tags:
      - user
      summary: "注册"
      description: "create a user"
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - Action
              - username
              - password
            properties:
              Action:
                type: string
                example: Register
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/getUserInfo:
    post:
      tags: 
      - user
      summary: "获取用户信息"
      parameters:
        - in: header
          name: jwtToken
          schema:
            type: string
          required: true
        - in: header
          name: refreshToken
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - Action
            properties:
              Action:
                type: string
                example: GetUserInfo
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
schemes:
 - https
 - http
